### ISSUE TITLE
Error when trying to run Mind Monitor - OSC Receiver Audio Feedback

### ISSUE THREAD

**Issue by JoshetaSrinivasan** [Enigma644/MindMonitorPython#1]
Hi, 
I tried running theOSC Receiver Audio Feedback code but got the following error when it ran. Any ideas on how to resolve it?

  

2021-06-12 11:24:30.349 Python[29165:7243071] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
        0   AppKit                              0x00007fff2f39a629 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
        1   AppKit                              0x00007fff2f382052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
        2   AppKit                              0x00007fff2f381ac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        3   _macosx.cpython-38-darwin.so        0x000000010b94d750 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 80
        4   _macosx.cpython-38-darwin.so        0x000000010b950c5f FigureManager_init + 319
        5   Python                              0x0000000104833e9c wrap_init + 12
        6   Python                              0x00000001047e5769 wrapperdescr_call + 121
        7   Python                              0x00000001047dc955 _PyObject_MakeTpCall + 373
        8   Python                              0x00000001048aaeb5 call_function + 533
        9   Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        10  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        11  Python                              0x00000001047dc7a7 _PyObject_FastCallDict + 247
        12  Python                              0x00000001047dddaf _PyObject_Call_Prepend + 143
        13  Python                              0x0000000104833de1 slot_tp_init + 145
        14  Python                              0x000000010482f2b9 type_call + 297
        15  Python                              0x00000001047dc955 _PyObject_MakeTpCall + 373
        16  Python                              0x00000001048aaeb5 call_function + 533
        17  Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        18  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        19  Python                              0x00000001047df96a method_vectorcall + 170
        20  Python                              0x00000001048aae5c call_function + 444
        21  Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        22  Python                              0x00000001048abca4 _PyEval_EvalCodeWithName + 2804
        23  Python                              0x00000001047dd43e _PyFunction_Vectorcall + 270
        24  Python                              0x00000001047dfa4c method_vectorcall + 396
        25  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        26  Python                              0x00000001048a8178 _PyEval_EvalFrameDefault + 26968
        27  Python                              0x00000001048abca4 _PyEval_EvalCodeWithName + 2804
        28  Python                              0x00000001047dd43e _PyFunction_Vectorcall + 270
        29  Python                              0x00000001048aae5c call_function + 444
        30  Python                              0x00000001048a7cfa _PyEval_EvalFrameDefault + 25818
        31  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        32  Python                              0x00000001048aae5c call_function + 444
        33  Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        34  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        35  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        36  Python                              0x00000001048a8178 _PyEval_EvalFrameDefault + 26968
        37  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        38  Python                              0x00000001048aae5c call_function + 444
        39  Python                              0x00000001048a7c49 _PyEval_EvalFrameDefault + 25641
        40  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        41  Python                              0x00000001048aae5c call_function + 444
        42  Python                              0x00000001048a7c49 _PyEval_EvalFrameDefault + 25641
        43  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        44  Python                              0x00000001047df9ab method_vectorcall + 235
        45  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        46  Python                              0x000000010494a1da t_bootstrap + 74
        47  Python                              0x00000001048fdaa9 pythread_wrapper + 25
        48  libsystem_pthread.dylib             0x00007fff6c39e109 _pthread_start + 148
        49  libsystem_pthread.dylib             0x00007fff6c399b8b thread_start + 15
)
Listening on UDP port 5000
2021-06-12 11:24:30.443 Python[29165:7243071] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
2021-06-12 11:24:30.443 Python[29165:7243071] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1677.205/Foundation/Misc.subproj/NSUndoManager.m:363
2021-06-12 11:24:30.445 Python[29165:7243071] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1677.205/Foundation/Misc.subproj/NSUndoManager.m:363
2021-06-12 11:24:30.447 Python[29165:7243071] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff32177657 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff6aff15bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff321a07f8 +[NSException raise:format:arguments:] + 88
        3   Foundation                          0x00007fff34892e7d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
        4   Foundation                          0x00007fff347cf5ce +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 440
        5   AppKit                              0x00007fff2f35c65c -[NSApplication run] + 864
        6   _macosx.cpython-38-darwin.so        0x000000010b9520d2 show + 210
        7   Python                              0x0000000104819356 cfunction_vectorcall_NOARGS + 214
        8   Python                              0x00000001048aae5c call_function + 444
        9   Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        10  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        11  Python                              0x00000001048aae5c call_function + 444
        12  Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        13  Python                              0x00000001048abca4 _PyEval_EvalCodeWithName + 2804
        14  Python                              0x00000001047dd43e _PyFunction_Vectorcall + 270
        15  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        16  Python                              0x00000001048a8178 _PyEval_EvalFrameDefault + 26968
        17  Python                              0x00000001048abca4 _PyEval_EvalCodeWithName + 2804
        18  Python                              0x00000001047dd43e _PyFunction_Vectorcall + 270
        19  Python                              0x00000001047df9ab method_vectorcall + 235
        20  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        21  Python                              0x00000001048a8178 _PyEval_EvalFrameDefault + 26968
        22  Python                              0x00000001048abca4 _PyEval_EvalCodeWithName + 2804
        23  Python                              0x00000001047dd43e _PyFunction_Vectorcall + 270
        24  Python                              0x00000001048aae5c call_function + 444
        25  Python                              0x00000001048a7c6d _PyEval_EvalFrameDefault + 25677
        26  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        27  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        28  Python                              0x00000001048a8178 _PyEval_EvalFrameDefault + 26968
        29  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        30  Python                              0x00000001048aae5c call_function + 444
        31  Python                              0x00000001048a7c49 _PyEval_EvalFrameDefault + 25641
        32  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        33  Python                              0x00000001048aae5c call_function + 444
        34  Python                              0x00000001048a7c49 _PyEval_EvalFrameDefault + 25641
        35  Python                              0x00000001047dd2a0 function_code_fastcall + 128
        36  Python                              0x00000001047df9ab method_vectorcall + 235
        37  Python                              0x00000001047dcc7d PyVectorcall_Call + 109
        38  Python                              0x000000010494a1da t_bootstrap + 74
        39  Python                              0x00000001048fdaa9 pythread_wrapper + 25
        40  libsystem_pthread.dylib             0x00007fff6c39e109 _pthread_start + 148
        41  libsystem_pthread.dylib             0x00007fff6c399b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      /usr/local/bin/python

**Comment by Enigma644** [comment]
I guess multi-threading the plot doesn't work on Unix like it does on Windows.

```
if __name__ == "__main__":
    #Tread for plot render - Note this generates a warning, but works fine
    thread = threading.Thread(target=init_plot)
```

I'm not sure how to fix this, sorry. On Windows you get the below warning, but it all works fine:

```
Listening on UDP port 5000
C:\Users\James\source\repos\MindMonitorPython\OSC Receiver Audio Feedback.py:118: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  ani = FuncAnimation(plt.gcf(), plot_update, interval=100)
C:\Users\James\source\repos\MindMonitorPython\OSC Receiver Audio Feedback.py:120: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.show()
```

**Comment by JoshetaSrinivasan** [comment]
I see, I tried editing the code so that it simply prints out the relative values of the brain waves in the format <delta, theta, alpha, beta, gamma>.  However, when I run it I only get the following output: 

-1,-1,-1,-1,-1
Listening on UDP port 5000

Here's the code (P.s. I'm very new to OSC so I don't entirely know what I'm doing; I can't tell if there's something wrong with the code or if I simply am not receiving the data at all) 

"""
Mind Monitor - OSC Receiver Audio Feedback
Coded: James Clutterbuck (2021)
Requires: python-osc, math, playsound, matplotlib, threading
"""
from pythonosc import dispatcher
from pythonosc import osc_server
import math
from playsound import playsound
# import time
import threading
# import sys

#Network Variables
ip = "10.0.0.44"
port = 5000

#Muse Variables
hsi = [4,4,4,4]
hsi_string = ""
abs_waves = [-1,-1,-1,-1,-1]
rel_waves = [-1,-1,-1,-1,-1]

#Audio Variables
alpha_sound_threshold = 0.6
sound_file = "bell.mp3"

#Plot Array
plot_val_count = 200
plot_data = [[0],[0],[0],[0],[0]]

#Muse Data handlers
def hsi_handler(address: str,*args):
    global hsi, hsi_string
    hsi = args
    if ((args[0]+args[1]+args[2]+args[3])==4):
        hsi_string_new = "Muse Fit Good"
    else:
        hsi_string_new = "Muse Fit Bad on: "
        if args[0]!=1:
            hsi_string_new += "Left Ear. "
        if args[1]!=1:
            hsi_string_new += "Left Forehead. "
        if args[2]!=1:
            hsi_string_new += "Right Forehead. "
        if args[3]!=1:
            hsi_string_new += "Right Ear."        
    if hsi_string!=hsi_string_new:
        hsi_string = hsi_string_new
        print(hsi_string)    
          
def abs_handler(address: str,*args):
    global hsi, abs_waves, rel_waves
    wave = args[0][0]
    
    #If we have at least one good sensor
    if (hsi[0]==1 or hsi[1]==1 or hsi[2]==1 or hsi[3]==1):
        if (len(args)==2): #If OSC Stream Brainwaves = Average Onle
            abs_waves[wave] = args[1] #Single value for all sensors, already filtered for good data
        if (len(args)==5): #If OSC Stream Brainwaves = All Values
            sumVals=0
            countVals=0            
            for i in [0,1,2,3]:
                if hsi[i]==1: #Only use good sensors
                    countVals+=1
                    sumVals+=args[i+1]
            abs_waves[wave] = sumVals/countVals
            
        rel_waves[wave] = math.pow(10,abs_waves[wave]) / (math.pow(10,abs_waves[0]) + math.pow(10,abs_waves[1]) + math.pow(10,abs_waves[2]) + math.pow(10,abs_waves[3]) + math.pow(10,abs_waves[4]))
        # update_plot_vars(wave)
        if (wave==2 and len(plot_data[0])>10): #Wait until we have at least 10 values to start testing
            test_alpha_relative()

#Audio test
def test_alpha_relative():
    alpha_relative = rel_waves[2]
    if (alpha_relative>alpha_sound_threshold):
        print ("BEEP! Alpha Relative: "+str(alpha_relative))
        playsound(sound_file)        

# Print relative strings
def printWaves():
    global rel_waves
    print("{},{},{},{},{}".format(rel_waves[0],rel_waves[1], rel_waves[2], rel_waves[3], rel_waves[4]))

        
#Main
if __name__ == "__main__":
    #Tread for plot render - Note this generates a warning, but works fine
    thread = threading.Thread(target=printWaves())
    thread.daemon = True
    thread.start()
    
    #Init Muse Listeners    
    dispatcher = dispatcher.Dispatcher()
    dispatcher.map("/muse/elements/horseshoe", hsi_handler)
    
    dispatcher.map("/muse/elements/delta_absolute", abs_handler,0)
    dispatcher.map("/muse/elements/theta_absolute", abs_handler,1)
    dispatcher.map("/muse/elements/alpha_absolute", abs_handler,2)
    dispatcher.map("/muse/elements/beta_absolute", abs_handler,3)
    dispatcher.map("/muse/elements/gamma_absolute", abs_handler,4)

    server = osc_server.ThreadingOSCUDPServer((ip, port), dispatcher)
    print("Listening on UDP port "+str(port))
    server.serve_forever()

**Comment by JoshetaSrinivasan** [comment]
I see, I tried editing the code so that it simply prints out the relative values of the brain waves in the format <delta, theta, alpha, beta, gamma>.  However, when I run it I only get the following output: 

-1,-1,-1,-1,-1
Listening on UDP port 5000

Here's the code (P.s. I'm very new to OSC so I don't entirely know what I'm doing; I can't tell if there's something wrong with the code or if I simply am not receiving the data at all) 

[test.txt](https://github.com/Enigma644/MindMonitorPython/files/6649132/test.txt)

**Comment by Enigma644** [comment]
In your code printWaves only runs once.
This code is specifically designed to plot a graph and if that doesn't work on Unix, then there's no point using this as your starting point. Play with the Receiver, or Receiver Simple code instead.
Brainwaves come in at 10Hz, so there's far too much data to pump out as text on the screen.

**Comment by JoshetaSrinivasan** [comment]
Ah I see! So I did try running the simple receiver code and all I got was the following output. I changed the ip address to my local address and updated that on the mind-monitor app. My firewall is turned off too. So, I don't know why there isn't any data being printed. 

<img width="934" alt="Screenshot 2021-06-14 at 1 18 26 PM" src="https://user-images.githubusercontent.com/77361949/121932561-019bea00-cd13-11eb-8747-5f7f7a17ca5d.png">


Thank you for all the quick responses btw! Like I said, I'm no expert; so I really appreciate the patience.

**Comment by Enigma644** [comment]
Don't edit the IP in the code. Leave it at 0.0.0.0; that means to listen locally.
You only need to put your computer's local WiFi IP in Mind Monitor.

**Comment by JoshetaSrinivasan** [comment]
Still no avail: 

<img width="1200" alt="Screenshot 2021-06-14 at 2 56 28 PM" src="https://user-images.githubusercontent.com/77361949/121944471-b38de300-cd20-11eb-86e9-336fa376dfe1.png">

![IMG_1560](https://user-images.githubusercontent.com/77361949/121944554-c7394980-cd20-11eb-909d-789c0fdd738b.PNG)

**Comment by Enigma644** [comment]
Are you sure you're using the correct local IP? You can find it with the ifconfig command.

**Comment by Enigma644** [comment]
I'm closing this issue as there's been no response in 3 months. If you're still having problems, please email me, but I don't believe there is an issue with the python code.
