### ISSUE TITLE
Can't get OSC Streaming Data

### ISSUE THREAD

**Issue by rizaru22** [Enigma644/MindMonitorPython#2]
Hi James.
I can't get the OSC Streaming Data when I try the code
it was printed 'Listening on UDP port 5000', but the RAW EEG data didn't show up.
any suggestion for me?

Thankyou before

**Comment by Enigma644** [comment]
Did you close this because you figured it out?

**Comment by rizaru22** [comment]
yes, I try before, but can't get any clue...
maybe a lost a few step...

2022-02-24 06:45:03.010509,807.069580078125,852.6007080078125,830.8424682617188,806.6666870117188,935.6043701171875


can i get an explanation about this raw data...

thankyou.

**Comment by Enigma644** [comment]
That's RAW EEG in MicroVolts.
Year-Month-Day Hour:Minute:Second.Microsecond TP9, AF7, AF8, TP10, AUX
See the OSC spec on the website here: https://mind-monitor.com/FAQ.php#oscspec

**Comment by rizaru22** [comment]
Thankyou so much.
