### ISSUE TITLE
How do you send marker to control recording?

### ISSUE THREAD

**Issue by Semayuki** [Enigma644/MindMonitorPython#3]
Bottom of the OSC Receiver.py, I added the following codes.
`client = udp_client.SimpleUDPClient("0.0.0.0", 5009)
  client.send_message("/Marker/1", 1) # start recording
    client.send_message("/Marker/2", 2) # end recording`

But it never records eeg on csv.
Please let me know how to send markers.
Thank you.

**Comment by Enigma644** [comment]
You send Markers via Mind Monitor. The above code will not work, it's the wrong port and server.serve_forever() is blocking.

Enable "Marker Buttson" in settings and you will get five numbered buttons to press while streaming/recording.
