### ISSUE TITLE
Why Am I getting 5 values from RAW EEG?

### ISSUE THREAD

**Issue by patricio1979** [Enigma644/MindMonitorPython#4]
I'm getting raw EEG five values from muse 1 (2016) as

865.092 855.421 855.421 854.212 1006.92
765.165 850.989 847.766 812.711 662.418
821.575 853.407 853.81 844.139 646.3
922.308 869.121 856.63 880 985.971
900.549 874.762 867.912 890.476 1070.99
789.744 869.524 869.524 841.722 734.542
811.905 879.194 873.956 838.095 597.949

In the example code it appears that the starting value is in the form of a timeStamp, but here it does not look like it.
Am I missing something?

**Comment by Enigma644** [comment]
Please see the OSC data spec:
https://mind-monitor.com/FAQ.php#oscspec
The 2016 Muse 1 (MU-02) has TP9, AF7, AF8, TP10, AUX

**Comment by patricio1979** [comment]
I'm not using AUX, only the first four
