### ISSUE TITLE
Binaries, L/R discretization Ratio Threshold please 

### ISSUE THREAD

**Issue by IkkAlpha** [Enigma644/MindMonitorPython#6]
For example when gamma on left front sensor exceeds one on right over the last 30s 
Reference for gamma training https://www.sciencedirect.com/science/article/abs/pii/S0167876009002682
Applied on a moving average of 30s, updated with average power calculated over 0.125s
set to the power level that would be surpassed 75% of the time during the preceding 30s window.
attempt to increase the rate of the tone occurrences. The maximum rate of the tones was set to one tone per second.

**Comment by Enigma644** [comment]
The whole point of this repo is to enable people to implement whatever they like, so sure. Go for it ;-)

**Comment by IkkAlpha** [comment]
That was fast. I updated the original message.
